### ISSUE TITLE
Test Accessing Datapoints

### ISSUE THREAD

**Issue by ayersdecker** [ayersdecker/AlertBoss-API#1]
Ensure all traffic is properly flowing

**Comment by xairen** [comment]
Integration for each method needs to be setup on AWS API Gateway

**Comment by ayersdecker** [comment]
Will look into it after Weds meeting

> Integration for each method needs to be setup on AWS API Gateway

**Comment by ayersdecker** [comment]
Adjusting this to API EC2 with more updates coming to API after Db update
